# Generated by Django 3.1.7 on 2021-04-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=500)),
                ('Correctop', models.CharField(max_length=100)),
                ('wrongop1', models.CharField(max_length=100)),
                ('wrongop2', models.CharField(max_length=100)),
                ('wrongop3', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('computer', 'computer'), ('GK', 'GK'), ('animals', 'animals'), ('geography', 'geography'), ('history', 'history')], max_length=9)),
            ],
        ),
    ]
