# Generated by Django 3.1.7 on 2021-04-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='desc',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
