# Generated by Django 3.1.7 on 2021-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
