# Generated by Django 3.1.7 on 2021-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_auto_20210422_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.TimeField(),
        ),
    ]
