# Generated by Django 3.1.7 on 2021-04-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20210422_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
